// Generated by CoffeeScript 1.8.0
var ConfigHelper,
  __hasProp = {}.hasOwnProperty;

ConfigHelper = (function() {
  var instance;

  function ConfigHelper() {}

  instance = null;

  ConfigHelper.getInstance = function() {
    return instance != null ? instance : instance = new ConfigHelper();
  };

  ConfigHelper.prototype.getPumpCount = function(cfg) {
    if (cfg.pumps != null) {
      return cfg.pumps.length;
    }
    return 0;
  };

  ConfigHelper.prototype.getRecipesCount = function(cfg) {
    var k;
    return ((function() {
      var _ref, _results;
      _ref = cfg.recipes;
      _results = [];
      for (k in _ref) {
        if (!__hasProp.call(_ref, k)) continue;
        _results.push(k);
      }
      return _results;
    })()).length;
  };

  ConfigHelper.prototype.getRecipes = function(cfg) {
    if (!cfg.recipes) {
      return {};
    }
    return cfg.recipes;
  };

  ConfigHelper.prototype.getPumps = function(cfg) {
    if (cfg.pumps == null) {
      return [];
    }
    return cfg.pumps;
  };

  return ConfigHelper;

})();
