// Generated by CoffeeScript 1.8.0
var eat, food, xxx, _i, _len;

food = ["apfel", "bannane"];

for (_i = 0, _len = food.length; _i < _len; _i++) {
  xxx = food[_i];
  eat(xxx, "marko");
}

eat = function(bla, mensch) {
  return console.log("das war aber lecker " + bla + " meint " + mensch);
};
